limits:
  artists: 15
  songs: 5
artists:
  - The Clash
  - The Offspring
  - Pearl Jam
  - Roxette
  - Elvis Presley
  - The Beatles
  - Imagine Dragons
  - Ratt
  - Morrissey
  - Bruno Mars
  - Twisted Sisters
  - Legião Urbana
  - Raimundos
  - Titãs
  - Capital Inicial
  - Os Paralamas do Sucesso
  - Rita Lee
  - Raul Seixas
  - System of a Down
  - Foo Fighters
  - The Dreadnoughts
  - Pitty
  - Jimi Hendrix
  - Jim Morrison
  - Skid row
  - Snow Patrol
  - Alice in chains
  - Rhapsody Of Fire
  - Detonautas Roque Clube
  - Avenged Sevenfold
  - Papa Roach
  - Nat King Cole
  - Supercombo
  - Paramore
  - Racionais MC\'s
  - Projota
  - Linkin Park
  - Audio Slave
  - Van Halen
  - KISS
  - Triumph
  - Unisonic
  - Slash
  - Aerosmith
  - Iron Maiden
  - Charlie Brown Jr.
  - Nightwish
  - Helloween
  - Chris Isaak
  - Coldplay
  - Eluveitie
  - Ozzy Osborn
  - Led Zeppelin
  - Queen
  - Black Sabbath
  - Dio
  - U2
  - Judas Priest
  - DragonForce
  - Raimundos
  - Tarja
  - The Doors
  - Pink Floyd
  - Deep Purple
  - Ramones
  - Rush
  - Rainbow
  - The Who
  - Roupa Nova
  - Johny Cash
  - Heart
  - Kansas
  - Bon Jovi
  - Guns N\' Roses
  - Duran Duran
  - Def Leppard
  - Whitesnake
  - Boston
  - Dio
  - Creedence Clearwater Revival
  - Eric Clapton
  - Stratovarius
  - Megadeath
  - Metallica
  - Alok
  - Jon Bon Jovi
  - Engenheiros do Hawaii
  - Scorpions
  - Desireless
  - Otep
  - Alestorm
  - Amaranthe
  - Leaves\' Eyes
  - Blind Guardian
  - Ira!
  - Cássia Eller
  - Elton John
  - The Hives
  - Fleetwood Mac
  - Hammer Fall
  - Sex Pistols
  - Cigarettes After Sex
  - Eagles
  - O Rappa
  - Arctic Monkeys
  - Greta Van Fleet
  - The Killers
  - Stone Sour
  - Soundgarden
  - Accept
  - Angra
  - Santana
  - Motörhead
  - Turisas
  - Anthrax
  - Freedom Call
  - Korpiklaani
  - Powerwolf
  - Dark Moor
  - Avantasia
  - Iggy Pop
  - Bruce Springsteen
  - Alice Cooper
  - Edguy
  - The Weeknd
  - Journey
  - Frank Sinatra
  - Slipknot
  - Five Finger Death Punch
  - Myrath
  - Elvenking
  - Rammstein
  - KSHMR
  - KVSH
  - Avicii
  - Sia
  - David Guetta
  - Rob Zombie
  - Powerglove
  - Gotthard
  - Sonata Arctica
  - Delain
  - Alter Bridge
  - Poison
  - Jefferson Airplane
  - Europe
  - Oasis
  - Nazareth
  - Tove Lo
  - Bee Gees
  - Zeca Baleiro
  - Bob Dylan
  - Korn
  - Os Paralamas do Sucesso
  - Epica
  - FLOW
  - Justin Timberlake
  - Ultraje a Rigor
  - REO Speedwagon
  - Dream Theater
  - The Beach Boys
  - ABBA
  - a-ha
  - dith Piaf
  - Studio Killers
  - Johnny Rivers
  - BABYMETAL
  - ANIMETAL
  - Slayer
  - Genesis
  - Sepultura
  - Sabaton
  - Blue Öyster Cult
  - Nickelback
  - Tihuana
  - Pedra Leticia
  - Matanza
  - Red Hot Chili Peppers
  - The Cure
  - AC/DC
  - Within Temptation
  - Pantera
  - Foster the People
  - Volbeat
